# This will start the Kotlin API and the infrastructure
version: "3.9"
include:
  - docker-compose.yaml
services:
  kotlinapi:
    build:
      context: ./source/kotlinExampleApi
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    environment:
      - otelCollector=http://otel-collector:4317
    volumes:
      - ~/.gradle:/home/gradle/.gradle
